# coding: utf-8

"""
    StockX API

    PRERELEASE API - Subject to change before release. Provides access to StockX's public services, allowing end users to query for product and order information.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import io_stockx
from io_stockx.models.product_response_product import ProductResponseProduct  # noqa: E501
from io_stockx.rest import ApiException


class TestProductResponseProduct(unittest.TestCase):
    """ProductResponseProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductResponseProduct(self):
        """Test ProductResponseProduct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = io_stockx.models.product_response_product.ProductResponseProduct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
