<?php
/**
 * PortfolioResponsePortfolioItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  StockX\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * StockX API
 *
 * Provides access to StockX's public services, allowing end users to query for product and order information.
 *
 * OpenAPI spec version: final32218.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace StockX\Client;

/**
 * PortfolioResponsePortfolioItemTest Class Doc Comment
 *
 * @category    Class */
// * @description PortfolioResponsePortfolioItem
/**
 * @package     StockX\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PortfolioResponsePortfolioItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PortfolioResponsePortfolioItem"
     */
    public function testPortfolioResponsePortfolioItem()
    {
    }

    /**
     * Test attribute "chain_id"
     */
    public function testPropertyChainId()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "sku_uuid"
     */
    public function testPropertySkuUuid()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }

    /**
     * Test attribute "action_by"
     */
    public function testPropertyActionBy()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "expires_at"
     */
    public function testPropertyExpiresAt()
    {
    }

    /**
     * Test attribute "expires_at_time"
     */
    public function testPropertyExpiresAtTime()
    {
    }

    /**
     * Test attribute "gain_loss_dollars"
     */
    public function testPropertyGainLossDollars()
    {
    }

    /**
     * Test attribute "gain_loss_percentage"
     */
    public function testPropertyGainLossPercentage()
    {
    }

    /**
     * Test attribute "market_value"
     */
    public function testPropertyMarketValue()
    {
    }

    /**
     * Test attribute "matched_state"
     */
    public function testPropertyMatchedState()
    {
    }

    /**
     * Test attribute "purchase_date"
     */
    public function testPropertyPurchaseDate()
    {
    }

    /**
     * Test attribute "purchase_date_time"
     */
    public function testPropertyPurchaseDateTime()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "status_message"
     */
    public function testPropertyStatusMessage()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "created_at_time"
     */
    public function testPropertyCreatedAtTime()
    {
    }

    /**
     * Test attribute "refer_url"
     */
    public function testPropertyReferUrl()
    {
    }

    /**
     * Test attribute "can_edit"
     */
    public function testPropertyCanEdit()
    {
    }

    /**
     * Test attribute "can_delete"
     */
    public function testPropertyCanDelete()
    {
    }

    /**
     * Test attribute "tracking"
     */
    public function testPropertyTracking()
    {
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }
}
