<?php
/**
 * PortfolioResponsePortfolioItemProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  StockX\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * StockX API
 *
 * Provides access to StockX's public services, allowing end users to query for product and order information.
 *
 * OpenAPI spec version: final32218.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace StockX\Client;

/**
 * PortfolioResponsePortfolioItemProductTest Class Doc Comment
 *
 * @category    Class */
// * @description PortfolioResponsePortfolioItemProduct
/**
 * @package     StockX\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PortfolioResponsePortfolioItemProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PortfolioResponsePortfolioItemProduct"
     */
    public function testPortfolioResponsePortfolioItemProduct()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "charity_condition"
     */
    public function testPropertyCharityCondition()
    {
    }

    /**
     * Test attribute "colorway"
     */
    public function testPropertyColorway()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "country_of_manufacture"
     */
    public function testPropertyCountryOfManufacture()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "content_group"
     */
    public function testPropertyContentGroup()
    {
    }

    /**
     * Test attribute "minimum_bid"
     */
    public function testPropertyMinimumBid()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "primary_category"
     */
    public function testPropertyPrimaryCategory()
    {
    }

    /**
     * Test attribute "secondary_category"
     */
    public function testPropertySecondaryCategory()
    {
    }

    /**
     * Test attribute "product_category"
     */
    public function testPropertyProductCategory()
    {
    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "retail_price"
     */
    public function testPropertyRetailPrice()
    {
    }

    /**
     * Test attribute "shoe"
     */
    public function testPropertyShoe()
    {
    }

    /**
     * Test attribute "short_description"
     */
    public function testPropertyShortDescription()
    {
    }

    /**
     * Test attribute "style_id"
     */
    public function testPropertyStyleId()
    {
    }

    /**
     * Test attribute "ticker_symbol"
     */
    public function testPropertyTickerSymbol()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "data_type"
     */
    public function testPropertyDataType()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "size_title"
     */
    public function testPropertySizeTitle()
    {
    }

    /**
     * Test attribute "size_descriptor"
     */
    public function testPropertySizeDescriptor()
    {
    }

    /**
     * Test attribute "size_all_descriptor"
     */
    public function testPropertySizeAllDescriptor()
    {
    }

    /**
     * Test attribute "url_key"
     */
    public function testPropertyUrlKey()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "shipping_group"
     */
    public function testPropertyShippingGroup()
    {
    }

    /**
     * Test attribute "a_lim"
     */
    public function testPropertyALim()
    {
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "parent_uuid"
     */
    public function testPropertyParentUuid()
    {
    }

    /**
     * Test attribute "size_sort_order"
     */
    public function testPropertySizeSortOrder()
    {
    }

    /**
     * Test attribute "shoe_size"
     */
    public function testPropertyShoeSize()
    {
    }

    /**
     * Test attribute "market"
     */
    public function testPropertyMarket()
    {
    }
}
