<?php
/**
 * ProductInfoProductAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  StockX\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * StockX API
 *
 * Provides access to StockX's public services, allowing end users to query for product and order information.
 *
 * OpenAPI spec version: final32218.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace StockX\Client;

/**
 * ProductInfoProductAttributesTest Class Doc Comment
 *
 * @category    Class */
// * @description ProductInfoProductAttributes
/**
 * @package     StockX\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductInfoProductAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductInfoProductAttributes"
     */
    public function testProductInfoProductAttributes()
    {
    }

    /**
     * Test attribute "product_category"
     */
    public function testPropertyProductCategory()
    {
    }

    /**
     * Test attribute "url_key"
     */
    public function testPropertyUrlKey()
    {
    }

    /**
     * Test attribute "slug"
     */
    public function testPropertySlug()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "ticker"
     */
    public function testPropertyTicker()
    {
    }

    /**
     * Test attribute "style_id"
     */
    public function testPropertyStyleId()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "size_locale"
     */
    public function testPropertySizeLocale()
    {
    }

    /**
     * Test attribute "size_title"
     */
    public function testPropertySizeTitle()
    {
    }

    /**
     * Test attribute "size_descriptor"
     */
    public function testPropertySizeDescriptor()
    {
    }

    /**
     * Test attribute "size_all_descriptor"
     */
    public function testPropertySizeAllDescriptor()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "minimum_bid"
     */
    public function testPropertyMinimumBid()
    {
    }

    /**
     * Test attribute "uniq_bids"
     */
    public function testPropertyUniqBids()
    {
    }

    /**
     * Test attribute "primary_category"
     */
    public function testPropertyPrimaryCategory()
    {
    }

    /**
     * Test attribute "secondary_category"
     */
    public function testPropertySecondaryCategory()
    {
    }
}
