<?php
/**
 * ProductResponseProductChildrenPRODUCTIDMarketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  StockX\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * StockX API
 *
 * Provides access to StockX's public services, allowing end users to query for product and order information.
 *
 * OpenAPI spec version: final32218.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace StockX\Client;

/**
 * ProductResponseProductChildrenPRODUCTIDMarketTest Class Doc Comment
 *
 * @category    Class */
// * @description ProductResponseProductChildrenPRODUCTIDMarket
/**
 * @package     StockX\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductResponseProductChildrenPRODUCTIDMarketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductResponseProductChildrenPRODUCTIDMarket"
     */
    public function testProductResponseProductChildrenPRODUCTIDMarket()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "sku_uuid"
     */
    public function testPropertySkuUuid()
    {
    }

    /**
     * Test attribute "product_uuid"
     */
    public function testPropertyProductUuid()
    {
    }

    /**
     * Test attribute "lowest_ask"
     */
    public function testPropertyLowestAsk()
    {
    }

    /**
     * Test attribute "lowest_ask_size"
     */
    public function testPropertyLowestAskSize()
    {
    }

    /**
     * Test attribute "number_of_asks"
     */
    public function testPropertyNumberOfAsks()
    {
    }

    /**
     * Test attribute "sales_this_period"
     */
    public function testPropertySalesThisPeriod()
    {
    }

    /**
     * Test attribute "sales_last_period"
     */
    public function testPropertySalesLastPeriod()
    {
    }

    /**
     * Test attribute "highest_bid"
     */
    public function testPropertyHighestBid()
    {
    }

    /**
     * Test attribute "highest_bid_size"
     */
    public function testPropertyHighestBidSize()
    {
    }

    /**
     * Test attribute "number_of_bids"
     */
    public function testPropertyNumberOfBids()
    {
    }

    /**
     * Test attribute "annual_high"
     */
    public function testPropertyAnnualHigh()
    {
    }

    /**
     * Test attribute "annual_low"
     */
    public function testPropertyAnnualLow()
    {
    }

    /**
     * Test attribute "deadstock_range_low"
     */
    public function testPropertyDeadstockRangeLow()
    {
    }

    /**
     * Test attribute "deadstock_range_high"
     */
    public function testPropertyDeadstockRangeHigh()
    {
    }

    /**
     * Test attribute "volatility"
     */
    public function testPropertyVolatility()
    {
    }

    /**
     * Test attribute "deadstock_sold"
     */
    public function testPropertyDeadstockSold()
    {
    }

    /**
     * Test attribute "price_premium"
     */
    public function testPropertyPricePremium()
    {
    }

    /**
     * Test attribute "average_deadstock_price"
     */
    public function testPropertyAverageDeadstockPrice()
    {
    }

    /**
     * Test attribute "last_sale"
     */
    public function testPropertyLastSale()
    {
    }

    /**
     * Test attribute "last_sale_size"
     */
    public function testPropertyLastSaleSize()
    {
    }

    /**
     * Test attribute "sales_last72_hours"
     */
    public function testPropertySalesLast72Hours()
    {
    }

    /**
     * Test attribute "change_value"
     */
    public function testPropertyChangeValue()
    {
    }

    /**
     * Test attribute "change_percentage"
     */
    public function testPropertyChangePercentage()
    {
    }

    /**
     * Test attribute "abs_change_percentage"
     */
    public function testPropertyAbsChangePercentage()
    {
    }

    /**
     * Test attribute "total_dollars"
     */
    public function testPropertyTotalDollars()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "last_lowest_ask_time"
     */
    public function testPropertyLastLowestAskTime()
    {
    }

    /**
     * Test attribute "last_highest_bid_time"
     */
    public function testPropertyLastHighestBidTime()
    {
    }

    /**
     * Test attribute "last_sale_date"
     */
    public function testPropertyLastSaleDate()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "deadstock_sold_rank"
     */
    public function testPropertyDeadstockSoldRank()
    {
    }

    /**
     * Test attribute "price_premium_rank"
     */
    public function testPropertyPricePremiumRank()
    {
    }

    /**
     * Test attribute "average_deadstock_price_rank"
     */
    public function testPropertyAverageDeadstockPriceRank()
    {
    }

    /**
     * Test attribute "featured"
     */
    public function testPropertyFeatured()
    {
    }
}
