<?php
/**
 * SearchHitTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  StockX\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * StockX API
 *
 * Provides access to StockX's public services, allowing end users to query for product and order information.
 *
 * OpenAPI spec version: final32218.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace StockX\Client;

/**
 * SearchHitTest Class Doc Comment
 *
 * @category    Class */
// * @description SearchHit
/**
 * @package     StockX\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchHitTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchHit"
     */
    public function testSearchHit()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "thumbnail_url"
     */
    public function testPropertyThumbnailUrl()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "product_category"
     */
    public function testPropertyProductCategory()
    {
    }

    /**
     * Test attribute "ticker_symbol"
     */
    public function testPropertyTickerSymbol()
    {
    }

    /**
     * Test attribute "style_id"
     */
    public function testPropertyStyleId()
    {
    }

    /**
     * Test attribute "make"
     */
    public function testPropertyMake()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "short_description"
     */
    public function testPropertyShortDescription()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "colorway"
     */
    public function testPropertyColorway()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "highest_bid"
     */
    public function testPropertyHighestBid()
    {
    }

    /**
     * Test attribute "total_dollars"
     */
    public function testPropertyTotalDollars()
    {
    }

    /**
     * Test attribute "lowest_ask"
     */
    public function testPropertyLowestAsk()
    {
    }

    /**
     * Test attribute "last_sale"
     */
    public function testPropertyLastSale()
    {
    }

    /**
     * Test attribute "sales_last_72"
     */
    public function testPropertySalesLast72()
    {
    }

    /**
     * Test attribute "deadstock_sold"
     */
    public function testPropertyDeadstockSold()
    {
    }

    /**
     * Test attribute "quality_bid"
     */
    public function testPropertyQualityBid()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "new_release"
     */
    public function testPropertyNewRelease()
    {
    }

    /**
     * Test attribute "searchable_traits"
     */
    public function testPropertySearchableTraits()
    {
    }

    /**
     * Test attribute "object_id"
     */
    public function testPropertyObjectId()
    {
    }

    /**
     * Test attribute "annual_high"
     */
    public function testPropertyAnnualHigh()
    {
    }

    /**
     * Test attribute "annual_low"
     */
    public function testPropertyAnnualLow()
    {
    }

    /**
     * Test attribute "deadstock_range_low"
     */
    public function testPropertyDeadstockRangeLow()
    {
    }

    /**
     * Test attribute "deadstock_range_high"
     */
    public function testPropertyDeadstockRangeHigh()
    {
    }

    /**
     * Test attribute "average_deadstock_price"
     */
    public function testPropertyAverageDeadstockPrice()
    {
    }

    /**
     * Test attribute "change_value"
     */
    public function testPropertyChangeValue()
    {
    }
}
