# coding: utf-8

"""
    StockX API

    PRERELEASE API - Subject to change before release. Provides access to StockX's public services, allowing end users to query for product and order information.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "stockx-api"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.11", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="StockX API",
    author_email="",
    url="",
    keywords=["Swagger", "StockX API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    PRERELEASE API - Subject to change before release. Provides access to StockX&#39;s public services, allowing end users to query for product and order information.  # noqa: E501
    """
)
