# coding: utf-8

"""
    StockX API

    PRERELEASE API - Subject to change before release. Provides access to StockX's public services, allowing end users to query for product and order information.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PortfolioResponsePortfolioItemProductMedia(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'image_url': 'str',
        'small_image_url': 'str',
        'thumb_url': 'str',
        'has360': 'bool',
        'key360': 'str'
    }

    attribute_map = {
        'image_url': 'imageUrl',
        'small_image_url': 'smallImageUrl',
        'thumb_url': 'thumbUrl',
        'has360': 'has360',
        'key360': 'key360'
    }

    def __init__(self, image_url=None, small_image_url=None, thumb_url=None, has360=None, key360=None):  # noqa: E501
        """PortfolioResponsePortfolioItemProductMedia - a model defined in Swagger"""  # noqa: E501

        self._image_url = None
        self._small_image_url = None
        self._thumb_url = None
        self._has360 = None
        self._key360 = None
        self.discriminator = None

        if image_url is not None:
            self.image_url = image_url
        if small_image_url is not None:
            self.small_image_url = small_image_url
        if thumb_url is not None:
            self.thumb_url = thumb_url
        if has360 is not None:
            self.has360 = has360
        if key360 is not None:
            self.key360 = key360

    @property
    def image_url(self):
        """Gets the image_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501


        :return: The image_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this PortfolioResponsePortfolioItemProductMedia.


        :param image_url: The image_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :type: str
        """

        self._image_url = image_url

    @property
    def small_image_url(self):
        """Gets the small_image_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501


        :return: The small_image_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :rtype: str
        """
        return self._small_image_url

    @small_image_url.setter
    def small_image_url(self, small_image_url):
        """Sets the small_image_url of this PortfolioResponsePortfolioItemProductMedia.


        :param small_image_url: The small_image_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :type: str
        """

        self._small_image_url = small_image_url

    @property
    def thumb_url(self):
        """Gets the thumb_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501


        :return: The thumb_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :rtype: str
        """
        return self._thumb_url

    @thumb_url.setter
    def thumb_url(self, thumb_url):
        """Sets the thumb_url of this PortfolioResponsePortfolioItemProductMedia.


        :param thumb_url: The thumb_url of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :type: str
        """

        self._thumb_url = thumb_url

    @property
    def has360(self):
        """Gets the has360 of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501


        :return: The has360 of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :rtype: bool
        """
        return self._has360

    @has360.setter
    def has360(self, has360):
        """Sets the has360 of this PortfolioResponsePortfolioItemProductMedia.


        :param has360: The has360 of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :type: bool
        """

        self._has360 = has360

    @property
    def key360(self):
        """Gets the key360 of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501


        :return: The key360 of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :rtype: str
        """
        return self._key360

    @key360.setter
    def key360(self, key360):
        """Sets the key360 of this PortfolioResponsePortfolioItemProductMedia.


        :param key360: The key360 of this PortfolioResponsePortfolioItemProductMedia.  # noqa: E501
        :type: str
        """

        self._key360 = key360

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PortfolioResponsePortfolioItemProductMedia):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
