# coding: utf-8

"""
    StockX API

    PRERELEASE API - Subject to change before release. Provides access to StockX's public services, allowing end users to query for product and order information.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PortfolioResponsePortfolioItemTracking(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'delivery_date_time': 'bool'
    }

    attribute_map = {
        'delivery_date_time': 'deliveryDateTime'
    }

    def __init__(self, delivery_date_time=None):  # noqa: E501
        """PortfolioResponsePortfolioItemTracking - a model defined in Swagger"""  # noqa: E501

        self._delivery_date_time = None
        self.discriminator = None

        if delivery_date_time is not None:
            self.delivery_date_time = delivery_date_time

    @property
    def delivery_date_time(self):
        """Gets the delivery_date_time of this PortfolioResponsePortfolioItemTracking.  # noqa: E501


        :return: The delivery_date_time of this PortfolioResponsePortfolioItemTracking.  # noqa: E501
        :rtype: bool
        """
        return self._delivery_date_time

    @delivery_date_time.setter
    def delivery_date_time(self, delivery_date_time):
        """Sets the delivery_date_time of this PortfolioResponsePortfolioItemTracking.


        :param delivery_date_time: The delivery_date_time of this PortfolioResponsePortfolioItemTracking.  # noqa: E501
        :type: bool
        """

        self._delivery_date_time = delivery_date_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PortfolioResponsePortfolioItemTracking):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
